### ISSUE TITLE
Please document how this differs from octohatrack

### ISSUE THREAD

**Issue by sigmavirus24** [pydanny/contributors#8]
[octohatrack](/LABHR/octohatrack) already collects information about contributors (on many axes) to a repository. Please document in the README how this differs from that.

**Comment by pydanny** [comment]
This project gathers contributors from multiple projects, rather than just one in the way octohatrack does (or maybe it does, I haven't really looked at either project since this issue helped kill my enthusiasm for doing any open source work).

 If you want to see this in the README, open a pull request.
